# 服务配置信息
server:
  port: 8000
  undertow:
    accesslog:
      dir: logs/
      enabled: true
  error:
    whitelabel:
      enabled: false
  connection-timeout: 10000
  compression:
    enabled: true

# 日志配置信息
logging:
  path: logs/
  file: mini.log

# redis配置信息
spring:
  redis:
    port: 5001
    host: 120.77.250.15
    password: college2018
    database: 0
    pool:
      min-idle: 5
      max-idle: 10
      max-active: 20
      max-wait: 3000

# 小程序配置信息
wx:
  url: https://api.weixin.qq.com/sns/jscode2session
  app-id: wxff85936696326ada
  app-secret: f9801e2aad4ba981e595791728a425d4

# shiro配置信息
luwei:
  module:
    shiro:
      prefix: college
      cache-days: 10
      cors-url: /mini/authorize

# 管理后台端口
guns:
  admin:
    port: 8001
