spring:
  data:
    mongodb:
      primary:
        host: localhost
        port: 27017
        database: test
        username: root
        password: root
      secondary:
        host: localhost
        port: 27017
        database: test
        username: root
        password: root