spring:
  data:
    mongodb:
      primary:
        host: 193.112.0.219
        port: 12017
        database: test
        username: root
        password: +tm8nsSBcpz/ayq"GbFEhoe(Jg4Z^.dN
      secondary:
        host: 193.112.0.219
        port: 12017
        database: test
        username: root
        password: +tm8nsSBcpz/ayq"GbFEhoe(Jg4Z^.dN