# 服务host配置
fantasy:
  mp: wxmps
  host: localhost
  nearjob: nearjob
  mp-index: https://mp.mariojd.cn

# 端口和日志配置
server:
  port: 10000
  undertow:
    accesslog:
      dir: logs
      enabled: true
      prefix: access.

# Jpa、Redis、Postgres和Elastic配置
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        # format_sql: true
        # session_factory:
        # interceptor: cn.mariojd.fantasy.nearjob.interceptor.TableInterceptor
        jdbc:
          lob:
            # @See: https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true
    open-in-view: false
  datasource:
    mp:
      url: jdbc:postgresql://${fantasy.host}:12432/${fantasy.mp}
      username: ${fantasy.mp}
      password: ${fantasy.mp}
      driver-class-name: org.postgresql.Driver
    nearjob:
      url: jdbc:postgresql://${fantasy.host}:12432/${fantasy.nearjob}
      username: ${fantasy.nearjob}
      password: ${fantasy.nearjob}
      driver-class-name: org.postgresql.Driver
  data:
    elasticsearch:
      cluster-nodes: ${fantasy.host}:9300
      cluster-name: docker-cluster
    web:
      pageable:
        max-page-size: 40
        default-page-size: 15
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: ${fantasy.host}
    port: 12379
    database: 3
    password: redis6379
  jackson:
    date-format: yyyy-MM-dd HH:mm
