server:
  port: 10000
  undertow:
    accesslog:
      dir: logs
      enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            # @See: https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:12432/nearjob
    username: nearjob
    password: nearjob
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: docker-cluster
    web:
      pageable:
        max-page-size: 20
        default-page-size: 15
  mvc:
    servlet:
      load-on-startup: 1
