spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:12432/nearjob
    username: nearjob
    password: nearjob
  data:
    elasticsearch:
      cluster-nodes: localhost:12900
