# 服务host配置
nearjob:
  host: localhost

# 端口和日志配置
server:
  port: 10000
  undertow:
    accesslog:
      dir: logs
      enabled: true
      prefix: access.

# Jpa、Redis、Postgres和Elastic配置
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        # format_sql: true
        session_factory:
          interceptor: cn.mariojd.nearjob.interceptor.TableInterceptor
        jdbc:
          lob:
            # @See: https://github.com/pgjdbc/pgjdbc/issues/1102
            non_contextual_creation: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${nearjob.host}:12432/nearjob
    username: nearjob
    password: nearjob
  data:
    elasticsearch:
      cluster-nodes: ${nearjob.host}:9300
      cluster-name: docker-cluster
    web:
      pageable:
        max-page-size: 20
        default-page-size: 15
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: ${nearjob.host}
    port: 12379
    database: 3
    password: redis6379
